spring:
  application:
    name: mcp-client
  ai:
    mcp:
      client:
        toolcallback:
          enabled: true


        enabled: true
        name: my-mcp-client
        version: 1.0.0
        request-timeout: 30s
        type: SYNC  # or ASYNC for reactive applications
        sse:
          connections:
            server1:
              url: http://localhost:8090

    # 以下为基于openai服务的配置信息
    openai:
      base-url: https://ark.cn-beijing.volces.com/api/
      api-key: 41532316-2144-4006-8bf3-7c5fd4a4e64d
      chat:
        options:
          model: deepseek-v3-250324 #doubao-1-5-pro-256k-250115


# 以下配置为基于ollama部署的模型的配置信息
#    ollama:
#      base-url: http://localhost:11434
#      chat:
#        model: qwen3:1.7b
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
